# Site settings

baseurl: '' # the subpath of your site, e.g. /blog/
url: 'https://daniellimberger.de' # the base hostname & protocol for your site

title: 'Jiannan Li'
author: 'Jiannan Li'

# flickr_user: '131006004@N06'
# flickr_api_key: adb4be93419edab991522b4fa92b7029

default_header_img_dimensions: 'width="1024" height="1024"'
default_thubmnail_img_dimensions: 'width="768" height="768"'

# Handling Reading
safe: true
encoding: utf-8

# Build settings
markdown: kramdown

# Outputting
exclude: [
  'cibuild',
  'Gemfile',
  'Gemfile.lock',
  'package.json',
  'README.md',
  'LICENSE',
  'vendor']

defaults:
  - scope:
      path: ''
    values:
      lang: en
      description: 'Personal website of Jiannan Li, a Toronto-based human-computer interaction researcher. It enlists his publications and contact information.'
  

# CSS Minification
sass:
  style: compressed
